### ISSUE TITLE
BUG: Search bar cover the first search result

### ISSUE THREAD

**Issue by qinyuhang** [Kapeli/Dash-iOS#110] opened 2019-11-02 05:26 UTC
Here in the picture, U can see the first item is covered by the bar, I marked it with red line.
![IMG_0179](https://user-images.githubusercontent.com/6239057/68066516-48beac80-fd74-11e9-8c2c-38870800ff82.jpeg)

**Comment by Kapeli** [comment] 2019-11-02 08:32
Duplicate of https://github.com/Kapeli/Dash-iOS/issues/99

**Closed by Kapeli** 2019-11-02 08:32 UTC
