### ISSUE TITLE
Correct way to add docs?

### ISSUE THREAD

**Issue by treyharris** [Kapeli/Dash-iOS#108] opened 2019-10-11 19:15 UTC
I just downloaded Dash to try it because someone recommended it to me, but getting started is very difficult—there are specific docs or docsets I’d like to use, but I can’t install them unless I can find a search that puts what I want in a list with other items, too. See this example interaction:

![IMG_0890](https://user-images.githubusercontent.com/97895/66678033-fa1c6780-ec38-11e9-80eb-df7f0b123020.gif)

If I stop typing “bash” at <kbd>b</kbd><kbd>a</kbd>, then I can install it. But add the <kbd>s</kbd>, and I can’t. And there are items like “Xamarin” that I can’t install at all without scrolling through the entire unfiltered list—simply typing <kbd>x</kbd> is enough to make it disappear.

I’m honestly not sure how this app is _supposed_ to be used—is there a recommended way for adding docsets that’s not this one? The initial intake UX of the app guides you to this place, so perhaps it needs to be changed?

**Comment by treyharris** [comment] 2019-10-11 19:28
Playing with this a bit more, I think it may be an off-by-one/indexing error you’ve made in this display. The filtered list displayed is [1..] based on a _zero-indexed_ list. So you actually only see the second, third, and so on results. And when it’s just one (like <kbd>b</kbd> <kbd>a</kbd> <kbd>s</kbd>, which can _only_ match “Bash”) you get no results at all.

So this seems like a trivial bug to fix, not a documentation issue after all!

**Comment by Kapeli** [comment] 2019-10-13 21:25
Duplicate of https://github.com/Kapeli/Dash-iOS/issues/99.

**Closed by Kapeli** 2019-10-13 21:25 UTC
